### ISSUE TITLE
Don't work with Figwheel

### ISSUE THREAD

**Issue by mauricioszabo** [clojure-expectations/expectations#100]
When I try to work with Figwheel, it gives me the warning:

```
Figwheel: Not loading code with warnings - target/js/cljs_deps.js
Figwheel: Compile Warning - expectations is a single segment namespace in file file:/home/mauricio/.m2/repository/expectations/expectations/2.2.0-rc3/expectations-2.2.0-rc3.jar!/expectations.cljc at line 1, column 1
```
I know I could just ignore warnings, but probably it's not a good idea when the fix would be relatively simple...

**Comment by seancorfield** [comment]
Changing the namespace would break backward compatibility so I can't do that.

**Comment by mauricioszabo** [comment]
So, any workaround?

**Comment by seancorfield** [comment]
Ignore the warnings?

**Comment by mauricioszabo** [comment]
Figwheel doesn't reload a file if it has warnings... also, sometimes, google closure compiler sometimes wouldn't load single segment ns, and there are a bunch of bugs in ClojureScript with this issue... doesn't seem right to add on every project that'll use `expectation` a line to ignore warning when it's discouraged by Clojure and ClojureScript. See discussion here: https://github.com/tonsky/datascript/issues/57

For now, I'm ignoring warnings from figwheel, so my code could reload again...

**Comment by seancorfield** [comment]
It's definitely unfortunate that `expectations` has always existed as a single-segment namespace.

When I added `expectations.clojure.test`, I did that as Clojure-only because a) I don't use ClojureScript and b) I don't know how to make a ClojureScript-compatible version of it (macros etc).

If you want to send a PR to copy `expectations` to `expectations.core` and have both `expectations` and `expectations.clojure.test` require that and import/intern all the symbols to maintain backward compatibility (and make sure all the clj and cljs tests still pass), I'd entertain that -- although I'm not sure cljs can do the intern thing?

But I'll be honest, cljs support has always been a bit of a pain in the @$$ as far as I'm concerned so it's low on my priority list 👎

**Comment by mauricioszabo** [comment]
Ok, I'll try something here and see if I can send you a PR.

Also, I agree with you: cljs support is indeed a pain...

**Comment by seancorfield** [comment]
If you have recommendations for unit-testing infrastructure for `.cljc` projects, I'm all ears!

**Comment by vmfhrmfoaj** [comment]
Hi @mauricioszabo 

I think You can fix the problem by adding `:warnings {:single-segment-namespace false}` to the  compiler option. See, https://clojurescript.org/reference/compiler-options#warnings

Here is my configuration:
```clojure
:cljsbuild
{:builds {:dev {:source-paths ["src" "spec" "test" "tool"]
                :compiler {:main {{ns-name}}.core
                           :asset-path "js/out"
                           :output-to  "resources/public/js/app.js"
                           :output-dir "resources/public/js/out"
                           :optimizations :none
                           :source-map-timestamp true
                           :warnings {:single-segment-namespace false}
                           :parallel-build true}
                :figwheel {:on-jsload dev.tool/on-reload
                           :websocket-host :js-client-host}}

          :prod {:source-paths ["src" "spec"]
                 :compiler {:output-to "resources/public/js/app.js"
                            :optimizations :advanced
                            :fn-invoke-direct false ; Need more performance? If yes, turn it on.
                            ;; :source-map "resources/public/js/app.js.map" ; Uncomment this for debugging.
                            :pretty-print false
                            :parallel-build true}
                 :warning-handlers
                 [(fn [type env extra]
                    (let [root (str (System/getProperty "user.dir") "/")
                          path (clojure.string/replace-first cljs.analyzer/*cljs-file* root "")]
                      (when (re-find #"/{{sanitized}}/" path)
                        (-> (cljs.analyzer/error-message type extra)
                            (str " at line " (:line env) " " cljs.analyzer/*cljs-file*)
                            (ex-info {:tag :cljs/analysis-error})
                            (throw)))))]}}}
```

In advance, I am sorry if I misunderstand the problem.
