### ISSUE TITLE
Missing where the test failure occurs

### ISSUE THREAD

**Issue by mmower** [clojure-expectations/expectations#83]
Hi.

Here's an example of an exception I get from expectations. The problem is that the exception doesn't reference any of my test code. In order to figure out where it was originating I had to comment out all my tests and re-introduce them one-by-one until it started failing.

I realise it's in a macro expansion which may make things more complicated but is there no way, other than searching as I have, for expectations to yield a reference to the test source code where the failure is located?

Or do you have any advice for working with macros in a different way? Am I making things unnecessarily difficult for myself? The context is refactoring some code that was under test and all green.

Matt

*************** Running tests ***************
:reloading (fate.search-test)
:error-while-loading fate.search-test
Error refreshing environment: java.lang.ClassCastException: java.lang.Long cannot be cast to clojure.lang.Named
 at clojure.core$name.invokeStatic (core.clj:1546)
    clojure.core$name.invoke (core.clj:1540)
    fate.search$__GT_component_slot.invokeStatic (search.cljc:55)
    fate.search$__GT_component_slot.invoke (search.cljc:50)
    fate.search$rewrite.invokeStatic (search.cljc:144)
    fate.search$rewrite.invoke (search.cljc:128)
    fate.search$search.invokeStatic (search.cljc:197)
    fate.search$search.invoke (search.cljc:153)
    clojure.lang.Var.invoke (Var.java:394)
    clojure.lang.AFn.applyToHelper (AFn.java:165)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.lang.Compiler.macroexpand1 (Compiler.java:6776)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6854)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.analyze (Compiler.java:6625)
    clojure.lang.Compiler$BodyExpr$Parser.parse (Compiler.java:6001)
    clojure.lang.Compiler$TryExpr$Parser.parse (Compiler.java:2277)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6868)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.analyze (Compiler.java:6625)
    clojure.lang.Compiler$BodyExpr$Parser.parse (Compiler.java:6001)
    clojure.lang.Compiler$FnMethod.parse (Compiler.java:5380)
    clojure.lang.Compiler$FnExpr.parse (Compiler.java:3972)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6866)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.analyze (Compiler.java:6625)
    clojure.lang.Compiler$InvokeExpr.parse (Compiler.java:3766)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6870)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.analyze (Compiler.java:6625)
    clojure.lang.Compiler$TryExpr$Parser.parse (Compiler.java:2248)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6868)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.access$300 (Compiler.java:38)
    clojure.lang.Compiler$LetExpr$Parser.parse (Compiler.java:6269)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6868)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6856)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6856)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.analyze (Compiler.java:6625)
    clojure.lang.Compiler$BodyExpr$Parser.parse (Compiler.java:6001)
    clojure.lang.Compiler$FnMethod.parse (Compiler.java:5380)
    clojure.lang.Compiler$FnExpr.parse (Compiler.java:3972)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6866)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6856)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.access$300 (Compiler.java:38)
    clojure.lang.Compiler$DefExpr$Parser.parse (Compiler.java:589)
    clojure.lang.Compiler.analyzeSeq (Compiler.java:6868)
    clojure.lang.Compiler.analyze (Compiler.java:6669)
    clojure.lang.Compiler.analyze (Compiler.java:6625)
    clojure.lang.Compiler.eval (Compiler.java:6931)
    clojure.lang.Compiler.load (Compiler.java:7379)
    clojure.lang.RT.loadResourceScript (RT.java:372)
    clojure.lang.RT.loadResourceScript (RT.java:363)
    clojure.lang.RT.load (RT.java:453)
    clojure.lang.RT.load (RT.java:419)
    clojure.core$load$fn__5677.invoke (core.clj:5893)
    clojure.core$load.invokeStatic (core.clj:5892)
    clojure.core$load.doInvoke (core.clj:5876)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invokeStatic (core.clj:5697)
    clojure.core$load_one.invoke (core.clj:5692)
    clojure.core$load_lib$fn__5626.invoke (core.clj:5737)
    clojure.core$load_lib.invokeStatic (core.clj:5736)
    clojure.core$load_lib.doInvoke (core.clj:5717)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$load_libs.invokeStatic (core.clj:5774)
    clojure.core$load_libs.doInvoke (core.clj:5758)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$require.invokeStatic (core.clj:5796)
    clojure.core$require.doInvoke (core.clj:5796)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.tools.namespace.reload$track_reload_one.invokeStatic (reload.clj:35)
    clojure.tools.namespace.reload$track_reload_one.invoke (reload.clj:21)
    clojure.tools.namespace.reload$track_reload.invokeStatic (reload.clj:52)
    clojure.tools.namespace.reload$track_reload.invoke (reload.clj:43)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.lang.Var.alterRoot (Var.java:303)
    clojure.core$alter_var_root.invokeStatic (core.clj:5299)
    clojure.core$alter_var_root.doInvoke (core.clj:5294)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    clojure.tools.namespace.repl$do_refresh.invokeStatic (repl.clj:94)
    clojure.tools.namespace.repl$do_refresh.invoke (repl.clj:82)
    clojure.tools.namespace.repl$refresh.invokeStatic (repl.clj:145)
    clojure.tools.namespace.repl$refresh.doInvoke (repl.clj:128)
    clojure.lang.RestFn.invoke (RestFn.java:397)
    autoexpect.runner$refresh_environment.invokeStatic (runner.clj:21)
    autoexpect.runner$refresh_environment.invoke (runner.clj:20)
    autoexpect.runner$run_tests.invokeStatic (runner.clj:88)
    autoexpect.runner$run_tests.invoke (runner.clj:86)
    autoexpect.runner$monitor_project$fn__1387.invoke (runner.clj:113)
    autoexpect.runner$monitor_project.invokeStatic (runner.clj:110)
    autoexpect.runner$monitor_project.doInvoke (runner.clj:106)
    clojure.lang.RestFn.invoke (RestFn.java:512)
    user$eval1390.invokeStatic (form-init2647085086146728351.clj:1)
    user$eval1390.invoke (form-init2647085086146728351.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6927)
    clojure.lang.Compiler.eval (Compiler.java:6917)
    clojure.lang.Compiler.load (Compiler.java:7379)
    clojure.lang.Compiler.loadFile (Compiler.java:7317)
    clojure.main$load_script.invokeStatic (main.clj:275)
    clojure.main$init_opt.invokeStatic (main.clj:277)
    clojure.main$init_opt.invoke (main.clj:277)
    clojure.main$initialize.invokeStatic (main.clj:308)
    clojure.main$null_opt.invokeStatic (main.clj:342)
    clojure.main$null_opt.invoke (main.clj:339)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)

**Comment by seancorfield** [comment]
There's nothing Expectations can do here to make your life easier: the exception comes from just loading the namespace -- when the Clojure compiler tries to compile it and the (presumably) macro-expansion fails because, based on the stacktrace, you're calling `fate.search/search` with a long when it's expecting a keyword:
```
fate.search$__GT_component_slot.invokeStatic (search.cljc:55)
fate.search$__GT_component_slot.invoke (search.cljc:50)
fate.search$rewrite.invokeStatic (search.cljc:144)
fate.search$rewrite.invoke (search.cljc:128)
fate.search$search.invokeStatic (search.cljc:197)
fate.search$search.invoke (search.cljc:153)
```
This happens when lein-autoexpect tries to reload namespaces for changed files -- Expectations hasn't even been invoked at this point. All lein-autoexpect knows is that when it tried to load `fate.search-test`, the compiler threw an exception.

I would recommend adopting a workflow where, when you save a file in your editor, you compile it into your REPL (in Emacs `C-c C-k` would do that) and that will highlight compilation errors in a better way.
