### ISSUE TITLE
Expect with double values

### ISSUE THREAD

**Issue by laliluna** [clojure-expectations/expectations#84]
The following test fails naturally

    (expect 0.33 (/ 1 3 ))

I could not find a nice way to express this with expectations. Do I overlook something?

If not and assuming I manage to provide a patch: How should it look like

     (expect (approximately 0.33) (/ 1 3))
 
Best Regards

Sebastian

**Comment by seancorfield** [comment]
I'd be happy with `approximately` as a function that took a value and returned a predicate that checked whether its argument was within a certain tolerance of the original value. I think it would be good to support two arities:

    (expect (approximately 0.33) (/ 1 3))
    (expect (approximately 0.33 0.01) (/ 1 3))

That way users can control the tolerance when the default doesn't work for them (and I'd probably expect the default tolerance to be 0.001 - 1/10th of a percent) so the first expectation would fail.

**Comment by asheldo** [comment]
In junit, there is a third arg, delta or epsilon, fwiw:
http://stackoverflow.com/questions/5686755/meaning-of-epsilon-argument-of-assertequals-for-double-values

**Comment by seancorfield** [comment]
Yup, that's why I suggested the 2-argument version of approximately so users can control the delta/epsilon.

**Comment by seancorfield** [comment]
I've pushed a 2.2.0-SNAPSHOT release to clojars.org containing this enhancement. 2.2.0-SNAPSHOT also includes the new `clojure.test` compatibility from #82.
