### ISSUE TITLE
Support for ^:slow labels on some tests

### ISSUE THREAD

**Issue by cloojure** [clojure-expectations/expectations#85]
Is it possible to extend expectations so that some tests (test.check for example) are labelled with ^:slow metadata, so that they are skipped unless invoked as:

    > lein expectations :all

The idea is something similar to https://github.com/technomancy/leiningen/blob/master/sample.project.clj#L340

Alan

**Comment by seancorfield** [comment]
There's currently no way to add metadata to tests as part of Expectations. It's something I want to add when I add named-test (`clojure.test`) support.

For now, what you can do is:

    (alter-meta! (expect e-val (a-expr)) assoc :slow true)

That still causes the "anonymous" function to be defined, and it looks like the metadata correctly has `:slow true` in it.

**Comment by seancorfield** [comment]
I'm going to close this -- since there's a workaround -- and fold the requirement into #82.
