### ISSUE TITLE
.cljc version is broken in several places

### ISSUE THREAD

**Issue by seancorfield** [clojure-expectations/expectations#86]
Revert to working .cljx version (2.1.4) and re-apply changes made since:

https://github.com/clojure-expectations/expectations/compare/ae8c2c5ffad62f86c6551ecc6b07a240229c5d3d...master

We can have another run at .cljc conversion later -- but it must maintain testability with zero failures.

**Comment by seancorfield** [comment]
This represents a baseline working version based on `cljx`: https://github.com/clojure-expectations/expectations/tree/back-to-clx

Unfortunately, it reverts the private atom changes in 2.1.4 (since those break in cljs) and it also won't work with any version of ClojureScript after 0.0-3308.

That latter restriction probably means that Expectations is useless to anyone doing ClojureScript development these days. The jump from 0.0-3308 to 1.8.x breaks on the `cljs?` macro so switching that to `if-cljs` per macrovich (@cgrand) might be the next logical step there.

**Comment by jaycfields** [comment]
Hey man, you're in charge so it's obviously your call, but you might want to consider just deleting all cljs related code. I don't believe there's a person on earth using expectations with cljs. It would be nice to have that option, but if it were me I'd delete all the current cljs code and bring in new code later if someone feels the need to support cljs.

My two cents.

**Comment by seancorfield** [comment]
I'm, definitely starting to lean that way! :)

I will probably have one small push forward with trying Christophe's suggestions to see if I can at least get the cljx version working with more recent versions of ClojureScript. If I can get past that, I can try to re-apply the handful of updates since 2.1.3 and get back to a working "modern" version of Expectations with cljx.

**Comment by seancorfield** [comment]
PR #87 had gotten the cjlc version into a state where all the tests pass (although `cljsbuild once` hangs). I'll push forward with version updates now and see if we can get this all running on recent ClojureScript versions.
