### ISSUE TITLE
A better way to assert multiple results

### ISSUE THREAD

**Issue by schmee** [clojure-expectations/expectations#88]
When testing, you often want to some relation of the input and output for a list of arguments. This can be achieved in expectations like this:

```clojure
(expect (more-of [arg result]
                 result (= result (some-result-fn arg))
        (from-each [arg [:a :b :c]]
          [arg (do-the-thing arg)]))
```

This method has some shortcomings. First and foremost: you lose the enhanced error reporting since you are comparing booleans, not types. Contrary to the rest of expectations the syntax looks and feels quite cryptic. There is also no example in the docs of this pattern.

Compare this to the clojure.test way of writing it with the `are` macro:

```clojure
(are [arg] (= (some-result-fn arg) (do-the-thing arg))
  :a
  :b
  :c)
```

I think that this operation is common enough to warrant dedicated syntax. While I don't have a concrete proposal, I think the `are` macro in clojure.test is a good starting point.

**Comment by seancorfield** [comment]
(I'm back from vacation now -- thank you for creating this as a reminder!)

One thing that did occur to me is that you could do:
```clojure
(expect #(= (do-the-thing %) (some-result-fn %))
        (from-each [arg [:a :b :c]] arg))
```
Still not ideal, I agree, but I think it's less convoluted than my suggestion of `more-of` from our Slack convo. And that gives me an idea -- let me try something...

**Comment by seancorfield** [comment]
OK, yes, you can do this:
```clojure
(expect (from-each [arg [:a :b :c]]
          (= (some-result-fn arg) (some-result-fn arg))))
```
That's concise, but still suffers from the lack of a good explanation on failures. More thought needed!

**Comment by jaycfields** [comment]
An earlier version of expectations had `given`, which allowed you to write
```clj
(given [x y z]
  (expect z (+ x y))
  1 2 3
  2 4 6
  3 3 6)
```
This led to a bunch of unreadable tests; it was rarely used for something straightforward. More often than not it led to a huge expect with a bunch going on, and a bunch of values below where often the values could not even be seen on the screen at the same time as the expect.

It was (and is) my opinion that you only end up needing this when you can't easily repeat the expect. In that case I think it's suboptimal to hide the issue with `are` or `given`, and your time is better spent making the domain code more friendly for multiple `expect`s.

There were a few people who missed given, and they defined their own. If I were still in charge of expectations that's what I'd be recommending, and I wouldn't add `given` (or something similar) to expectations. But, I'm not in charge, and maybe @seancorfield will add it with the caution that if you feel the need to use this, you may have detestable code.  Or maybe he'll disagree with my assertion that it facilitates less readable tests.

**Comment by jaycfields** [comment]
Those are my thoughts in general; for the specific example I wouldn't combine those two into one expect. 

To have a suggestion on what to write for a specific example, I'd need to have more context (I think). Just based on the example above, I'd abandon the from-each and write individual expectations.

```
(expect (more-of x
                 String (str x)
                 "a" (name x)
                 ":a" (str x))
  (identity :a))

(expect (more-of x
                 String (str x)
                 "b" (name x)
                 ":b" (str x))
  (identity :b))

(expect (more-of x
                 String (str x)
                 "c" (name x)
                 ":c" (str x))
  (identity :c))
```

**Comment by jaycfields** [comment]
There's also another option, but I worry about it's long term maintainability.

```
(expect nil
  (from-each [arg [:a :b :c]]
    (let [result (do-the-thing arg)]
      (when (not= result (some-result-fn arg))
        [arg result (some-result-fn arg)]))))
```

When that test fails you'll have all of the data, and can write an individual expectation to find why it's failing.

I use this pattern for testing config files that are created and edited by our support team. If they put a bad value in the config file the build breaks and the `actual` value from the expectation tells them what's wrong. Similar to this...

```
(expect nil
  (from-each [arg [:web :monitoring :compliance]]
    (let [result (get-in (load-config) [arg :port])]
      (when-not (instance? Long result)
        (format "the %s port needs to be a number, it's currently %s"
                (name arg)
                (pr-str result))))))
```

This works for generating errors our support team can work with without needing developer help. However, this wouldn't be my first test pattern choice for tests meant to help future code maintainers.

**Comment by seancorfield** [comment]
We used `given` fairly heavily at World Singles and when it went away, we just copied it to our "test.util" namespace and continued using it for a while, as we transitioned away from it. We no longer use it, and I agree with @jaycfields that tests are more readable without it. So, no, it won't be making a comeback in any form.

I _do_ however think there's value in `more-of` bindings being available in the "expected" expression but I haven't yet looked at the code to see whether that's feasible or even a desirable change to make. So I may yet convince myself that is not worth doing after all.

I _have_ run into the same problem that @schmee highlights here and I would like to figure out a general solution that is prettier than what is currently possible. Replacing `from-each` with individual `expect` forms is not always practical or desirable (if the sequence is long and/or complex to compute in the first place).

**Comment by jaycfields** [comment]
Understood. I really prefer expecting literals; if someone left me a from-each and more-of combo to maintain I'd be grumpy. That said, sometimes giving someone dynamite is exactly what they need.

Could a custom pred solve this exceptional case, rather than adding more to expectations?

**Comment by jaycfields** [comment]
an example of a custom pred https://github.com/jaycfields/simple-expectations/blob/master/test/simple_expectations/core_test.clj

**Comment by seancorfield** [comment]
The basic problem here is that there are times with `from-each` where you want both the item itself _and_ something computed from it, and the expected value is computed a different/simpler way from the item.

In some ways `from-each` is a red herring here because what we're really talking about is:
```clojure
(let [x (some-value)]
  (expect (simple-fn x) (actual-complex-fn x)))
```
(except done within the machinery of Expectations -- we used to have `expect-let` but that was removed in 2.1.4 -- interestingly I've felt the lack of that when adding `clojure.test` support via the `defexpect` macro where I've found I sometimes want a `let` inside that which wraps a bunch of `expect` calls (or pairs of expected/actual forms)... but I've resisted adding support for it precisely _because_ `expect-let` was removed... but I think there's a tension between `from-each` and the lack of `expect-let` that is surfacing in this issue)

**Comment by jaycfields** [comment]
Got it.

I think you can do 
```
(let [x (some-value)]
  (expect (simple-fn x) (actual-complex-fn x)))
```

with 

```
(defrecord SomePred []
    CustomPred
    (expect-fn [e a] 
        (= (simple-fn a) (actual-complex-fn a))
    (expected-message [e a str-e str-a] (str "expected:" (simple-fn a)))
    (actual-message [e a str-e str-a] (str "  actual:" (actual-complex-fn a)))
    (message [e a str-e str-a] (clojure.data/diff (simple-fn a) (actual-complex-fn a)))

(expect (->SomePred) (some-value))
```

I'm not suggesting that as a solution for relieving the tension you described, just trying to present options to help while you work on that.

**Comment by seancorfield** [comment]
The `CustomPred` stuff is completely(?) undocumented right now and it isn't intuitive (how exactly are the three message functions used? what are their arguments? etc) but it's good to know that this sort of extension point is available.

It looks pretty verbose and repetitive tho' for this use case (but maybe there's a way to "solve" this by providing a set of wrappers around `CustomPred` for this sort of use case so it's much easier to use?).

**Comment by seancorfield** [comment]
Given an appropriate wrapper function, we could reduce the original problem to:
```clojure
(expect (functionally simple-fn actual-complex-fn)
        (from-each [arg [:a :b :c]] arg))
```

**Comment by jaycfields** [comment]
I couldn't find any docs either. I guess I never doc'd it.

The msg functions are for printing pretty error messages. You have access to the args and their original data (e-str and a-str). The arg lists are the same as do-expect iirc. I don't think you'd write a custom pred for every expectation.. I think you'd want to write one generic one and reuse it. E.g. you'd write 

```
(defrecord Functionally [f1 f2]
    CustomPred
    (expect-fn [e a] 
        (= (f1 a) (f2 a))
    (expected-message [e a str-e str-a] (format "expected: %s from %s" (f1 a) f1))
    (actual-message [e a str-e str-a] (format "  actual: %s from %s" (f2 a) f2))
    (message [e a str-e str-a] (clojure.data/diff (simple-fn a) (actual-complex-fn a)))
```

Then you can write the expectations as

```
(expect (->Functionally simple-fn actual-complex-fn) :a)
(expect (->Functionally simple-fn actual-complex-fn) :b)
(expect (->Functionally simple-fn actual-complex-fn) :c)
```

Or use from-each.. but I think making a more complex yet concise expectation wouldn't be worth it now that you've reduced it to the custom pred. jmo

**Comment by jaycfields** [comment]
This...
```
(defrecord Functionally [f1 f2]
  CustomPred
  (expect-fn [e a]
    (= (f1 a) (f2 a)))
  (expected-message [e a str-e str-a] (format "expected: %s" (f1 a)))
  (actual-message [e a str-e str-a] (format "  actual: %s" (f2 a)))
  (message [e a str-e str-a] "not functionally eq"))

(expect-focused (->Functionally * +) 4)
(expect-focused (->Functionally str name) :a-sym)
```
results in 1 success and 1 failure. The failure gives this message
```
failure in (failure_examples.clj:146) : failure.failure-examples
           expected: :a-sym
             actual: a-sym
           not functionally eq
```

**Comment by seancorfield** [comment]
Now that I've made this work:
```clojure
(expect (functionally some-result-fn do-the-thing)
        (from-each [arg [:a :b :c]] arg))
```
I'm going to declare this "done" and cut 2.2.0-beta1.

**Comment by schmee** [comment]
Great discussion @seancorfield and @jaycfields, really cleared a lot of thing up for me.`functionally` looks very "expectations-y" and I'm going to give it a shot in my current project for sure.  

I don't really agree with your taken on `given` though. I think it puts the focus on what differs between each test, which is easy to lose track of when you copy-paste a test for each argument. But between `functionally` and `given` (which I can just copy into my project, as you mentioned) it looks like I'm all set for my multiple results.

Big thanks!
