### ISSUE TITLE
Question - how to map expect across a collection?

### ISSUE THREAD

**Issue by AndyKriger** [clojure-expectations/expectations#89]
A pattern that I often use in test-writing is map a validation function to every element in a sequence. In this case, I have an (expect (more-of...)) block that validates many things about a single element in a sequence. When I try to extract that block into a function and map that function across the sequence, it does not appear that any new tests are run (and a println in that new function suggests that it's not even being called).

Is there a way to use expect within a function mapped to a sequence?

```
(defn validation-fn [element]
    (expect (more-of part-of-element
                             ;; bunch of more-of expect clauses
                 )
                 (extract-value element)))

(map validation-fn my-sequence)
```

**Comment by jaycfields** [comment]
You'll probably need to provide more info for Sean.. but map is lazy so I don't think it's surprising you're not seeing it occur.

**Comment by seancorfield** [comment]
If you're on the Clojurians Slack, there's an #expectations channel which is a good place to ask questions.

The `expect` macro defines a function so you don't want it inside another function. I'd restructure this as a top-level `expect` that uses `from-each`, something like this:

    (expect (more-of part-of-element
              ;; bunch of expectations on part-of-element
            )
            (from-each [element my-sequence]
              (extract-value element)))

**Comment by AndyKriger** [comment]
Thank you - I stumbled on that solution just after posting the question. Glad to know what I found is the right approach.
