### ISSUE TITLE
Review Jake McCreary's test output analysis

### ISSUE THREAD

**Issue by seancorfield** [clojure-expectations/expectations#91]
http://jakemccrary.com/blog/2014/06/22/comparing-clojure-testing-libraries-output/

Re-run tests with `defexpect` to see what deteriorates and what can be done to improve the output.

**Comment by seancorfield** [comment]
The `defexpect` tests now have almost complete parity with the original `expect` tests but it would still be worth reviewing Jake's blog post and seeing where Expectations can be improved overall.

**Comment by jakemcc** [comment]
Great to hear that the output is nice again.

**Comment by seancorfield** [comment]
The `clojure.test` compatibility has been rewritten and moved to its own library. Since it now translates directly to `clojure.test`, it will have (almost) all of the same issues -- but it should be amenable to using Humane Test Output and other such libraries. This is no longer a relevant issue for Expectations itself.
