### ISSUE TITLE
Missing example for testing clojure spec definitions

### ISSUE THREAD

**Issue by witek** [clojure-expectations/expectations#99]
The documentation on https://clojure-expectations.github.io is missing an example how to test clojure spec definitions with expectations.

Especially, what spec function should be called the get the best error message on failed specs. s/valid? or s/conform or s/assert

**Comment by seancorfield** [comment]
Good suggestion! I'll have a think about that.

**Comment by seancorfield** [comment]
Just FYI, I'm looking at extending Expectations to support spec-based tests at this point since it already supports predicate-based tests.

**Comment by seancorfield** [comment]
If you use `clj` with the latest SHA of Expectations, you'll be able to do:

    (expect ::some-spec (some-expr))

if `::some-spec` is a registered spec. This is Clojure only right now. I'll try to get it working with ClojureScript before I cut the 2.1.11 release.
